import type {Metadata} from "next";
import "./globals.css";
import {ReactNode} from "react";
import Header from "@/app/header";
import Footer from "@/app/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  {
    children,
  }: Readonly<{
    children: ReactNode;
  }>) {
  return (
    <html lang="en">
      <body className={"bg-myblack text-white min-h-screen flex flex-col"}>
        <Header/>
        <Main>{children}</Main>
        <Footer/>
      </body>
    </html>
  );
}

const Main = ({children}: { children: ReactNode }) => {
  return (
    <>
      <div className={"flex-1 p-80 py-10"}>
        {children}
      </div>
    </>
  )
}

