import type {Metadata} from "next";
import "./globals.css";
import SearchBar from "@/components/SearchBar";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  {
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
  return (
    <html lang="en">
      <body className={"bg-myblack text-white"}>
        <Header/>
        <div>{children}</div>
        <Footer/>
      </body>
    </html>
  );
}

const Header = () => {

  return (
    <header className="border-b border-gray-500/30 flex items-center py-3 px-80 justify-between h-15">
      <div className="font-bold">
        <Link href={"/"}>Haisia&#39;s blog</Link>
      </div>
      <SearchBar/>
    </header>
  );
};

const Footer = () => {
  return (
    <>
      <footer>footer</footer>
    </>
  )
}